### ISSUE TITLE
Add upheno

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#1]
Upheno is available as OWL 
http://www.obofoundry.org/ontology/upheno.html

**Comment by caufieldjh** [comment]
May not be necessary and may introduce axiom conflicts - consider adding Mammalian Phenotype ontology (http://obofoundry.org/ontology/mp.html) instead

**Comment by matentzn** [comment]
Out of curiosity, what is your exact use case here?

**Comment by justaddcoffee** [comment]
Broadly speaking, the use cases we hope to support with KG-IDG are efforts to find drugs and drug targets to address human disease, as part of our participation in IDG. The idea in this ticket is to include an ontology like Upheno that would provide axioms that would link human data to other species, to better support these use cases

**Comment by matentzn** [comment]
I think since this is a bit more experimental, it would be great if you would use uPheno 2 for this use case. This gives you some level or cross species integration. If you consider this, I and @rays22 would support it!

**Comment by caufieldjh** [comment]
@matentzn I'd like to try adding uPheno 2. Is the alpha (https://zenodo.org/record/3710690/files/upheno_all_with_relations.owl) still the most recent stable version?

**Comment by caufieldjh** [comment]
Fantastic, thanks!
