### ISSUE TITLE
ATC ingest emits empty nodes/edges file

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-idg#105]
### Describe the bug

It looks as though ATC ingest emits empty nodes/edges file in the most recent build

### To Reproduce

See here for example:
https://kg-hub.berkeleybop.io/kg-idg/20220722/transformed/atc/index.html
Steps to reproduce the behavior.

## Expected behavior

Should emit nodes and edges files that aren't empty

### Version

This problem is present in 20220722, but not in 20220701 for example - possibly a new bug? 

https://kg-hub.berkeleybop.io/kg-idg/20220701/transformed/atc/index.html

### Additional context

I just happened upon this because we are thinking about using KG-IDG for a investigation into topological biases and graph ML

**Comment by caufieldjh** [comment]
Good catch, thanks. Suspect it's an issue with retrieval from Bioportal.

**Comment by caufieldjh** [comment]
_Not_ fixed by #110
