### ISSUE TITLE
Convert OWL ontologies to JSON

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#2]
Use ROBOT: https://robot.obolibrary.org/convert

**Comment by justaddcoffee** [comment]
We possibly could/should instead flesh this OWL -> KGX TSV in [kg-obo](https://github.com/Knowledge-Graph-Hub/kg-obo), and ingest from there

**Comment by caufieldjh** [comment]
Yes - that sounds better in the long term.

**Comment by justaddcoffee** [comment]
Adding myself as an assignee - let's hack together on a solution for this

**Comment by caufieldjh** [comment]
This is now handled by kg-obo.
