### ISSUE TITLE
Update GOCAMs to be less COVID specific

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-idg#34]
### Describe the desired behavior

Right now for the KG-IDG passthrough transform of GOCAMs, we are reusing the KG-COVID-19 transform of GOCAMs, which is derived from a big long SPARQL query described in [this ticket](https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/153). 

This is fairly COVID-19 specific, so we probably want a more general SPARQL query to retrieve GOCAMs for KG-IDG.

**Comment by caufieldjh** [comment]
Is the specific query (presumably with the bit about filtering for SARS-COV-2 uncommented)? https://github.com/Knowledge-Graph-Hub/kg-covid-19/issues/153#issuecomment-656738869

**Comment by caufieldjh** [comment]
For reference, the query in the link above is:
```
PREFIX biolink: <https://w3id.org/biolink/vocab/> 
PREFIX lego: <http://geneontology.org/lego/>
# Query for U-shaped patterns: 
# 
# al     a2 
# |      | 
# v      v 
# |      |
# b1--h--b2
#
# v has been constrained to RO:enabled_by 
#
CONSTRUCT { 
  # lifted edge 
  ?alc ?h ?a2c . 
  # reified edge linking to original molecular functions 
  _:edge rdf:type rdf:Statement . 
  _:edge lego:evidence ?model . 
  _:edge rdf:subject ?a1c . 
  _:edge rdf:predicate ?h . 
  _:edge rdf:object ?a2c . 
  _:edge biolink:subjectActivity ?b1c . 
  _:edge biolink:objectActivity ?b2c .
  }
WHERE { 
  # left side of U: constraining v to be RO:enabled_by
  ?b1 <http://purl.obolibrary.org/obo/R0_0002333, ?a1 .
  ?al rdf:type ?a1c .
  # constraining to the SARS-COV2/HOST model by matching namespace - is there a better way to do this? 
  #FILTER (CONTAINS(str(?b1), "http://model.geneontology.org/5e72450500004019")) 
  ?b1 rdf:type ?b1c . 
  # bottom of U 
  ?b1 ?h ?b2 .
  ?b2 rdf:type ?b2c .
  # right side of U: constraining v to be RO:enabled_by
  ?b2 <http://purl.obolibrary.org/obo/R0_0002333, ?a2 .
  ?a2 rdf:type ?a2c .
  # filter owl:NamedIndividual from the results 
  FILTER (!CONTAINS(str(?a1c), "NamedIndividual")) 
  FILTER (!CONTAINS(str(?a2c), "NamedIndividual")) 
  FILTER (!CONTAINs(str(?b1c), "NamedIndividual")) 
  FILTER (!CONTAINS(str(?b2c), "NamedIndividual")) 
  FILTER (!CONTAINS(str(?a1c), "NamedIndividual")) 
  FILTER (!CONTAINS(str(?a2c), "NamedIndividual")) 
  # bind the model (namespace) so that it can be returned
  BIND(URI(REPLACE(STR(?b1), "^(http://model.geneontology.org/.*?)/.*", "$1")) AS ?model) 
}
```

**Comment by caufieldjh** [comment]
I tried doing a direct conversion as follows:
1. Retrieve the entirety of the GO-CAMs from https://s3.amazonaws.com/geneontology-public/gocam/GO-CAMs.ttl.zip
2. Unzip
3. `robot convert --input GO-CAMs.ttl --output GO-CAMs.owl`
4. `kgx transform --input-format owl --output gocams --output-format tsv GO-CAMs.owl`
but this yielded a strangely assembled OWL and dumped everything into the nodesfile for the tsvs - not what we need.

**Comment by caufieldjh** [comment]
However, this process may work:
1. Retrieve the entirety of the GO-CAMs from https://s3.amazonaws.com/geneontology-public/gocam/GO-CAMs.ttl.zip
2. Unzip
3. `robot convert --input GO-CAMs.ttl --output GO-CAMs.json`
4. `kgx transform --input-format obo-json --output gocams --output-format tsv GO-CAMs.json`

**Comment by caufieldjh** [comment]
Should have read that kg-covid-19 issue thread more closely - should work with the `noctua-models` repo contents (https://github.com/geneontology/noctua-models)

**Comment by caufieldjh** [comment]
So it looks like the best next steps should be:
1. Include full reactome in KG-IDG
2. Clone `noctua-models`, master and dev branch
2. Produce blazegraph journal as per https://github.com/TranslatorIIPrototypes/cam-pipeline/blob/master/Makefile
3. Query journal as above to produce RDF
4. Ingest RDF -> tsv w/ KGX

**Comment by caufieldjh** [comment]
After setting up dependencies and running the Makefile (`make cam-db-reasoned.jnl`) I got a java error:
```
java.io.FileNotFoundException: blazegraph.properties
```
So I had to get it from here: https://github.com/NCATS-Tangerine/cam-pipeline/blob/master/blazegraph.properties

**Comment by caufieldjh** [comment]
In reviewing the current set of GO-CAMs, I notice three things:
* They may, in fact, be the set of *all* human GO-CAMs, not the COVID-specific set.
* The prefixes on all Reactome nodes are `:OBO:go/extensions/reacto.owl#REACTO_` though in the other KG-IDG Reactome imports it is `REACT:`
* All imported GO-CAM nodes are `biolink:NamedThing`

So the main issue here, of the imported GO-CAMs being COVID-19-specific, turns out to be a non-issue.
It would still be nice to have an updated set of GO-CAMs.

Integrating these nodes with the rest of the graph will require some prefix modifications and ideally some category updates for biolink types. Will close this issue once I've done that.

Could be another Koza transform.
