### ISSUE TITLE
Create more fine-grained STRING ingest based on Koza examples

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#37]
Koza has several examples for doing STRING ingests here: https://github.com/monarch-initiative/koza/tree/main/examples
The current ingest pulls the KG-COVID-19 STRING human PPI nodes/edges, but we could have more specific control over the desired STRING attributes by defining a Koza ingest.

**Comment by justaddcoffee** [comment]
We maybe should consider filtering out STRING edges with a combined score less than 0.7:

http://version10.string-db.org/help/faq/#how-to-extract-high-confidence-07-interactions-from-information-on-combined-score-in-proteinlinkstxtgz

**Comment by caufieldjh** [comment]
Luckily, that's in PR #33:
https://github.com/Knowledge-Graph-Hub/kg-idg/pull/33/commits/c8b02522c365e1f4d304201e564aa480160f5aa8

**Comment by justaddcoffee** [comment]
Okay, great! Should've known you'd done this already

**Comment by caufieldjh** [comment]
Upon closer examination, the current STRING ingest should be sufficient - corresponding nodes in the merged graph have xrefs to UniProtKB accessions and all edges are of the expected edge type (`biolink:interacts_with`) so this is enough unless/until we need more fine-grained interaction data.
