### ISSUE TITLE
Add ATC information about drugs from Drug Central

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-idg#42]
### Describe the desired behavior

We'd like to ingest ATC level 1 information for drugs, which Jeremy Yang says in [their SQL dump](http://juniper.health.unm.edu/tcrd/download/latest.sql.gz), in tables atc and struct2atc

## Additional context

Per discussion with Tudor and Jeremy and others on the IDG call just now

**Comment by caufieldjh** [comment]
May be helpful to load in the full ATC set here too
 https://bioportal.bioontology.org/ontologies/ATC

**Comment by caufieldjh** [comment]
I don't see the tables 'atc' or 'struct2atc' in the TCRD SQL dump linked above.
Perhaps they're in the DrugCentral dump: https://unmtid-shinyapps.net/download/drugcentral.dump.010_05_2021.sql.gz
(but I haven't looked yet)

**Comment by justaddcoffee** [comment]
Yeah, possibly they are in the DrugCentral sql dump you linked.

Might be worth a moment to ping Jeremy to confirm we are getting what we think we are getting

**Comment by caufieldjh** [comment]
TCRD uses MySQL, so of course DrugCentral uses PostgreSQL.
(A solvable issue.)
