### ISSUE TITLE
Create HTML index for graph_ml output

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-idg#62]
NEAT uploads its output to the `graph_ml/` directory for each build (e.g., `kg-idg/20211215/graph_ml/`).
This directory should also be indexed - the publish stage of the build calls `multi_indexer.py` to do this, and that will capture the graph_ml directory too but only if it's called after those new files are placed in the remote location.
We may also wrap up all the indexing and directory management code into its own script for the sake of neatness, then call that script once all new files have been produced.

**Comment by caufieldjh** [comment]
(This is in reference to #48)

**Comment by caufieldjh** [comment]
Also need to copy graph_ml output over to `current` directory

**Comment by justaddcoffee** [comment]
Arguably this functionality (writing index.html's) maybe should be NEAT's responsibility - what do you think?

**Comment by caufieldjh** [comment]
I think a case can be made for either approach, but at least for NEAT it seems that every future use case involves storage on S3, so it would make sense to have it write an index.html by default.
A third option is to have both KG-IDG and NEAT import indexing as a function stored in its own repository among other helpers.

**Comment by caufieldjh** [comment]
This will be NEAT's job, so closing.
